' Gambas module file

' This aplication is a part of Lobo Desktop 

' CPU-Info is an application that gathers information for hardware components available on your system.

' Copyright 2020(C) Lobo Desktop Team <lobodesktop@gmail.com>

' Authors:
'   Herberth Guzmán <herberthguzman@gmail.com>

' This program is free software: you can redistribute it and/or modify
' it under the terms of the GNU General Public License as published by
' the Free Software Foundation, either version 3 of the License, or
' (at your option) any later version.

' This program is distributed in the hope that it will be useful,
' but WITHOUT ANY WARRANTY; without even the implied warranty of
' MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
' GNU General Public License for more details.

' You should have received a copy of the GNU General Public License
' along with this program; If not, see <http://www.gnu.org/licenses/>.

'' NOTA
'' Check paths and libraries according to your Linux version.

iList As New String[] 
sNewList As New String[]

'' Dir
bDir As String = "/usr/bin/"
sbDir As String = "/usr/sbin/"
libDir As String = "/usr/lib/"

''Lib check
iListApps As String[] = ["x86_64-linux-gnu/libcpuinfo.so.0", "cpuid_tool", "libtoolize", "wmctrl", "hwinfo", "glxinfo", "lshw", "lsscsi"]

''Lib install
iListAppInstall As String[] = ["libcpuinfo0", "cpuidtool", "libtool", "wmctrl", "hwinfo", "mesa-utils", "lshw", "lsscsi"]
iDir As String[] = [libDir, bDir, bDir, bDir, sbDir, bDir, bDir, bDir]

Settings_Theme As New Settings(Desktop.ConfigDir &/ "CPU-Info" &/ "CPU-Info.conf")
sDir As String = Desktop.ConfigDir &/ "CPU-Info"
iResult As Integer

Public Sub Load()
  
  ''Load config and show form
  
  If Exist(sDir) And Exist(sDir &/ "CPU-Info.conf") Then
    Try iResult = Settings_Theme["Theme/iFull", FSystem]
    If iResult = 1 Then
      MCtl.Init_Form_Sys
      Inc Application.Busy
      MCtl.FillList
      Dec Application.Busy
    Else
      FSystemMini.Show
    Endif
    
  Else
    Try Mkdir sDir
    
    Settings_Theme.Write(FSystem)
    Settings_Theme["Theme/iFull"] = "1"
    Settings_Theme.Save
    Wait 0.1
    
    Settings_Theme.Reload
    Try iResult = Settings_Theme["Theme/iFull", FSystem]
    
    If iResult = 1 Then
      MCtl.Init_Form_Sys
      Inc Application.Busy
      MCtl.FillList
      Dec Application.Busy
    Else
      FSystemMini.Show
    Endif
    
  Endif
  
End

Public Sub Dependency()
  
  ''Check dependency
  Dim a As String
  Dim i As Integer = -1
  Dim sList As String
  
  For Each a In iListApps
    Inc i
    If Not (Exist(iDir[i] & iListApps[i])) Then
      
      If iListApps[i] Then  
        sNewList.Add(iListAppInstall[i], i)
      Endif 
      
      sList = sNewList.Join(Space(1))
      
    Endif
  Next
  
  If Not (sNewList.Count = 0) Then
    
    FCheck.Show
    Return
    
  Else
    
    MDependency.Load
    
  Endif
  
End
