' Gambas module file

' This aplication is a part of Lobo Desktop 

' CPU-Info is an application that gathers information for hardware components available on your system.

' Copyright 2020(C) Lobo Desktop Team <lobodesktop@gmail.com>

' Authors:
'   Herberth Guzmán <herberthguzman@gmail.com>

' This program is free software: you can redistribute it and/or modify
' it under the terms of the GNU General Public License as published by
' the Free Software Foundation, either version 3 of the License, or
' (at your option) any later version.

' This program is distributed in the hope that it will be useful,
' but WITHOUT ANY WARRANTY; without even the implied warranty of
' MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
' GNU General Public License for more details.

' You should have received a copy of the GNU General Public License
' along with this program; If not, see <http://www.gnu.org/licenses/>.

'' NOTA
'' Check paths and libraries according to your Linux version.

''Messages Publics

Public Const MSG_CN_DB As String = ("Error DB connection.")
Public Const MSG_CK_DEPENDENCY As String = ("All dependencies are installed, there is nothing to install...")   
Public Const MSG_NOT_UPDATE As String = ("No updates")
Public Const MSG_NW_VERSION_UPDATE As String = ("There is a new version, do you want to update?")
Public Const MSG_RD_DISK As String = ("Can't from read the source file or disk...") 
Public Const MSG_EMPTY_FIELDS As String = ("You cannot leave empty fields.") 
